# Day with most Homicides

In [14]:
library(httr)

# Pull the NewsroomDB URL from an environment variable so we don't expose our super-secret data feed ;-)
kNewsroomDbUrl <- Sys.getenv("NEWSROOMDB_URL")

# Download homicides CSV

r <- GET(paste0(kNewsroomDbUrl, "table/csv/homicides"))

# Load CSV into a dataframe
homicide.victims.csv <- content(r, "text")
con <- textConnection(homicide.victims.csv)
homicide.victims <- read.csv(con)
close(con)

# Parse some of the columns

# Convert the Date column to a date object
homicide.victims$Occ.Date <- as.Date(homicide.victims$Occ.Date, format="%Y-%m-%d")

# Extract the year from the date
homicide.victims$Year <- as.numeric(format(homicide.victims$Occ.Date,'%Y'))

In [15]:
library(dplyr)

# Get only 2016 homicide victims
homicide.victims.2016 <- filter(homicide.victims, Year == 2016)

# Group them by day
homicide.victims.2016.by.date <- group_by(homicide.victims.2016, Occ.Date)

# Count the homicide victims each day and sort in descending order
homicide.victims.2016.date.counts <- summarise(homicide.victims.2016.by.date, count = n()) %>%
  arrange(desc(count))

In [16]:
homicide.victims.2016.date.counts

    Occ.Date   count
1   2016-08-08 9
2   2016-09-05 9
3   2016-02-02 8
4   2016-08-23 8
5   2016-06-18 6
6   2016-08-14 6
7   2016-08-21 6
8   2016-01-25 5
9   2016-05-09 5
10  2016-05-15 5
11  2016-06-04 5
12  2016-06-16 5
13  2016-07-17 5
14  2016-07-28 5
15  2016-08-16 5
16  2016-08-28 5
17  2016-09-11 5
18  2016-09-18 5
19  2016-01-05 4
20  2016-01-08 4
21  2016-01-23 4
22  2016-01-31 4
23  2016-02-04 4
24  2016-02-13 4
25  2016-03-11 4
26  2016-03-15 4
27  2016-03-31 4
28  2016-04-07 4
29  2016-04-24 4
30  2016-04-30 4
⋮   ⋮          ⋮
195 2016-05-29 1
196 2016-06-02 1
197 2016-06-15 1
198 2016-06-22 1
199 2016-06-28 1
200 2016-06-30 1
201 2016-07-03 1
202 2016-07-09 1
203 2016-07-10 1
204 2016-07-15 1
205 2016-07-19 1
206 2016-07-23 1
207 2016-07-26 1
208 2016-08-01 1
209 2016-08-15 1
210 2016-08-17 1
211 2016-08-22 1
212 2016-09-01 1
213 2016-09-02 1
214 2016-09-07 1
215 2016-09-08 1
216 2016-09-09 1
217 2016-09-12 1
218 2016-09-14 1
219 2016-09-15 1
220 2016-09-19 1
221 2016-09-20 1
222 2016-09-22 1
223 2016-09-25 1
224 2016-09-27 1